### ISSUE TITLE
LIBUSB_ERROR_NOT_SUPPORTED: 

### ISSUE THREAD

**Issue by OwenBrotherwood** [OwenBrotherwood/EspruinoTools#1]
https://github.com/OwenBrotherwood/EspruinoTools/blob/c160d29b6cf0bdbdec02a7e3d85f462052aa6875/core/serial_noble.js#L10-L18

https://github.com/OwenBrotherwood/EspruinoTools/tree/LIBUSB_ERROR_NOT_SUPPORTED

https://github.com/sandeepmistry/noble/issues/502

May be fixed so would be nice without 

```
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_noble.js
here
'noble' module couldn't be loaded, no node.js Bluetooth Low Energy
 { Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Device.usb.Device.open (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\usb\usb.js:33:7)
    at BluetoothHciSocket.bindUser (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:81:19)
    at BluetoothHciSocket.bindRaw (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:28:8)
    at Hci.init (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\lib\hci-socket\hci.js:101:35)
    at NobleBindings.init (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at new Noble (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\lib\noble.js:50:18)
    at Object.<anonymous> (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\index.js:4:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) errno: -12 }
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_nodeserial.js

```

**Comment by OwenBrotherwood** [comment]
https://github.com/OwenBrotherwood/EspruinoTools/blob/1b56ce9bb792548ad908341ecc07f97eb8da8c5d/core/serial_noble.js#L11-L22

```
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_noble.js
No libusb - noble disabled
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_nodeserial.js
```

**Comment by OwenBrotherwood** [comment]
First test's have not indicated where the issue is, and I wouldn't understand anyway :)
So far, connect to puck.js

    // super nasty workaround for https://github.com/sandeepmistry/noble/issues/502
    // process.removeAllListeners('exit');
